### **Importing necessary libraries**

In [200]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

### **Loading the `weather_forecast.csv` dataset**

In [204]:
data = pd.read_csv("weather_forecast_data.csv")
print("Data loaded successfully.")
data.head()

Data loaded successfully.

   Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure     Rain
0    19.096119  71.651723   14.782324    48.699257   987.954760  no rain
1    27.112464  84.183705   13.289986    10.375646  1035.430870  no rain
2    20.433329  42.290424    7.216295     6.673307  1033.628086  no rain
3    19.576659  40.679280    4.568833    55.026758  1038.832300  no rain
4    19.828060  93.353211    0.104489    30.687566  1009.423717  no rain

### **Identifying the missing values in the dataset**

In [205]:
missing_values = data.isna().sum()
print("Missing values:\n", missing_values)

Missing values:
 Temperature    25
Humidity       40
Wind_Speed     32
Cloud_Cover    33
Pressure       27
Rain            0
dtype: int64

### **Handling missing values**

#### Using first techqnique (dropping missing values)

In [203]:
if missing_values.any():
    data = data.dropna(axis=0)
    print("Missing values dropped.")
    display(data.isna().sum())
else:
    print("No missing values found.")

Missing values dropped.

Temperature    0
Humidity       0
Wind_Speed     0
Cloud_Cover    0
Pressure       0
Rain           0
dtype: int64

#### Using second techqnique (replacing missing values with the average of the feature)

In [206]:
# Impute missing values in the dataset using the average of the feature column
if missing_values.any():
    for column in data.columns:
        if data[column].isna().any():
            data.fillna({column: data[column].mean()}, inplace=True)
    print("Missing values imputed.")
    display(data.isna().sum())
else:
    print("No missing values found.")

Missing values imputed.

Temperature    0
Humidity       0
Wind_Speed     0
Cloud_Cover    0
Pressure       0
Rain           0
dtype: int64

### **Checking if the data have the same scale**

In [207]:
print("Checking if the data have the same scale")
display(data.head())

Checking if the data have the same scale

   Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure     Rain
0    19.096119  71.651723   14.782324    48.699257   987.954760  no rain
1    27.112464  84.183705   13.289986    10.375646  1035.430870  no rain
2    20.433329  42.290424    7.216295     6.673307  1033.628086  no rain
3    19.576659  40.679280    4.568833    55.026758  1038.832300  no rain
4    19.828060  93.353211    0.104489    30.687566  1009.423717  no rain

### **Splitting the dataset into training and testing sets**

#### Separating the features and targets columns

In [208]:
target_columns = ["Rain"]
features = data.drop(columns=target_columns)
targets = data[target_columns]
print("Features and targets are separated.")
print("Features shape:", features.shape)
print("Targets shape:", targets.shape)

Features and targets are separated.
Features shape: (2500, 5)
Targets shape: (2500, 1)

#### Splitting the dataset into training and testing sets

In [209]:
x_train, x_test, y_train, y_test = train_test_split(features, targets, test_size=0.2, random_state=42, shuffle=True)
print("Data is shuffled and split.")
print("x_train shape:", x_train.shape)
print("x_test shape:", x_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

Data is shuffled and split.
x_train shape: (2000, 5)
x_test shape: (500, 5)
y_train shape: (2000, 1)
y_test shape: (500, 1)

### **Applying feature scaling after performing the train-test split**

In [210]:
scaler = StandardScaler()
numerical_columns = x_train.select_dtypes(include=[np.number]).columns
x_train[numerical_columns] = scaler.fit_transform(x_train[numerical_columns])
x_test[numerical_columns] = scaler.transform(x_test[numerical_columns])
print("Features are scaled.")
print("First five rows of x_train")
display(x_train.head())
print("\nFirst five rows of x_test")
display(x_test.head())

Features are scaled.
First five rows of x_train

      Temperature  Humidity  Wind_Speed  Cloud_Cover  Pressure
2055    -1.718125  1.687949    1.697663    -0.229740 -0.142129
1961     0.578604 -1.222505    1.195252     0.013527  1.749370
1864    -1.611123 -1.677586    0.944283    -0.392969  1.456590
2326    -1.293667  0.840139    1.180401     0.752595  0.044229
461     -1.366615  0.086746    0.063829     0.285025 -0.950329

First five rows of x_test

      Temperature  Humidity  Wind_Speed  Cloud_Cover  Pressure
1447    -0.439931  0.875070   -0.813364    -0.506291 -0.419847
1114    -1.725871 -0.290745   -1.281728    -0.091093 -1.481063
1064     1.166779  1.504868    0.490502    -1.364309  0.767471
2287    -1.184871  1.141692   -0.207549     0.641584  1.570095
1537     1.265119 -1.192291   -0.882951    -1.709711  1.253436